workspace:
  base: /go
  path: src/github.com/uswitch/vault-creds

pipeline:
  build:
    image: golang:1.9
    commands:
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-X main.sha ${DRONE_COMMIT_SHA}" -o bin/vaultcreds cmd/*.go
  
  docker-latest:
    image: plugins/docker
    repo: quay.io/uswitch/vault-creds
    registry: quay.io
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}
    when:
      event: push
      branch: master
  
  docker-tagged:
    when:
      event: tag
    image: plugins/docker
    repo: quay.io/uswitch/vault-creds
    registry: quay.io
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG}
